Use env vars to customise some scripts

diff --git a/030-flux b/030-flux
--- a/030-flux
+++ b/030-flux
@@ -10,11 +10,19 @@ onExit() {
 trap onExit EXIT
 
 # ensure that env GITHUB_USER and GITHUB_TOKEN are exported
+if [ -z "${GITHUB_USER}" -o -z "${GITHUB_TOKEN}" ]; then
+  echo "ERROR: Both GITHUB_USER and GITHUB_TOKEN must be set"
+  exit 1
+fi
+
+export GITHUB_REPO="${GITHUB_REPO:-eoepca-flux}"
+export GITHUB_BRANCH="${GITHUB_BRANCH:-main}"
+export GITHUB_PATH="${GITHUB_PATH:-deploy}"
 
 flux bootstrap github \
   --owner="${GITHUB_USER}" \
-  --repository="eoepca-flux" \
-  --branch="main" \
+  --repository="${GITHUB_REPO}" \
+  --branch="${GITHUB_BRANCH}" \
+  --path="${GITHUB_PATH}" \
   --private=false \
-  --personal=true \
-  --path="deploy"
+  --personal=true
